# Generated by Django 5.2.8 on 2026-10-07 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField()),
                ('image', models.URLField(blank=True, max_length=1000)),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('photo_caption', models.CharField(blank=True, max_length=240)),
                ('lead', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('read_time', models.CharField(default='3 min read', max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FarmerCoffeePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('robusta', 'Robusta'), ('arabica', 'Arabica')], max_length=20)),
                ('grade', models.CharField(max_length=100, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_30d_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['coffee_type', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='FarmerFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=120)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('coffee_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('financing', 'Financing'), ('training', 'Training'), ('certification', 'Certification'), ('input_discount', 'Input discount'), ('land', 'Land')], max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('detail', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('action_label', models.CharField(default='View details', max_length=80)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FarmerPortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('weather_temperature', models.DecimalField(decimal_places=1, default=24, max_digits=4)),
                ('weather_summary', models.CharField(default='Partly cloudy', max_length=160)),
                ('weather_guidance', models.TextField(blank=True)),
                ('dashboard_notice', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_required', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='FarmerCoffeeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('grade', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buyer', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_sales', to='api.farmerfarm')),
            ],
            options={
                'ordering': ['-delivery_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FarmerAgronomyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('detail', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agronomy_tasks', to='api.farmerfarm')),
            ],
            options={
                'ordering': ['status', 'due_date', '-is_urgent', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FarmerLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('cash', 'Cash loan'), ('fertilizer', 'Fertilizer loan')], max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coffee_grade', models.CharField(max_length=100)),
                ('coffee_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_coffee_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harvest_season', models.CharField(max_length=40)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='api.farmerfarm')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farmerfarm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='api.farmerprofile'),
        ),
        migrations.CreateModel(
            name='FarmerRewardBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('sustainability_score', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_balance', to='api.farmerfarm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerHarvestEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=40)),
                ('coffee_type', models.CharField(choices=[('robusta', 'Robusta'), ('arabica', 'Arabica')], max_length=20)),
                ('expected_quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_estimates', to='api.farmerfarm')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('farm', 'season', 'coffee_type'), name='unique_farmer_harvest_estimate')],
            },
        ),
        migrations.CreateModel(
            name='FarmerYieldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=40)),
                ('yield_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productivity_kg_per_acre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crop_health_score', models.PositiveSmallIntegerField(default=0)),
                ('tree_survival_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_records', to='api.farmerfarm')),
            ],
            options={
                'ordering': ['season'],
                'constraints': [models.UniqueConstraint(fields=('farm', 'season'), name='unique_farmer_farm_yield_season')],
            },
        ),
    ]
