# Generated by Django 5.2.8 on 2026-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_farmeradvice_farmercoffeeprice_farmerfarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
