from django.urls import path
from . import views
from . import farmer_views

urlpatterns = [
    path('health', views.health),
    path('account/sign-up', views.account_signup),
    path('account/sign-in', views.account_login),
    path('account/me', views.account_me),
    path('account/sign-out', views.account_logout),
    path('account/csrf', views.account_csrf),
    path('account/password-reset', views.request_password_reset),
    path('account/password-reset/confirm', views.confirm_password_reset),
    path('account/google/start', views.google_start),
    path('account/google/callback', views.google_callback),
    path('estate', views.estate),
    path('estate/invest', views.invest),
    path('orders', views.orders),
    path('contact', views.contact),
    path('newsletter/subscribe', views.newsletter_subscribe),
    path('blog/posts', views.blog_posts),
    path('chat', views.chat),
    path('chat/messages/<int:message_id>', views.chat_message_actions),
    path('chat/attachments/<int:message_id>', views.chat_attachment),
    path('chat/stream', views.chat_stream),
    path('lease-applications', views.lease_applications),
    path('farmer/auth/sign-up', farmer_views.farmer_sign_up),
    path('farmer/auth/sign-in', farmer_views.farmer_sign_in),
    path('farmer/auth/sign-out', farmer_views.farmer_sign_out),
    path('farmer/auth/me', farmer_views.farmer_me),
    path('farmer/dashboard', farmer_views.farmer_dashboard),
    path('farmer/performance', farmer_views.farmer_performance),
    path('farmer/prices', farmer_views.farmer_prices),
    path('farmer/agronomy', farmer_views.farmer_agronomy),
    path('farmer/agronomy/tasks/<int:task_id>', farmer_views.farmer_agronomy_task),
    path('farmer/harvest', farmer_views.farmer_harvest),
    path('farmer/harvest/estimates', farmer_views.farmer_harvest_estimate),
    path('farmer/harvest/sales', farmer_views.farmer_sale),
    path('farmer/opportunities', farmer_views.farmer_opportunities),
    path('farmer/rewards', farmer_views.farmer_rewards),
    path('farmer/advice', farmer_views.farmer_advice),
    path('farmer/advice/<slug:slug>', farmer_views.farmer_advice),
    path('farmer/loans', farmer_views.farmer_loans),
]